### PR TITLE
python2 to python3

### PR DESCRIPTION
**Pull request by jiapei100**
Python2 to Python3

### CODE REVIEW

**Comment by uricamic** [comment]
Hi, 

thanks for the pull request! Before merging it, since I am not a Python expert, I have to ask whether it is backwards compatible with Python2. If it is not, then I suggest creating a separate file for Python3.

**Comment by SamyCookie** [comment]
Hi,
Change seem good to me.
But I think it will be safer to prevent behaviour issues with print function by adding the future import, i.e.
`from __future __ import print_function`

**Comment by jiapei100** [comment]
To tell the truth, I only use a single command "2to3" to deal with the incompatibility ~ your original python code is clear enough...
And, BTW, clandmark works fine. However, I seriously do NOT like rapidxml, particularly, when I realize there are some declaration faults. You can just change to libxml2 or xmlparser, etc.

**Comment by uricamic** [comment]
Ok, I am merging the changes then. 

Yeah, I have chosen rapidxml just because it was the easiest solution at the given time, due to the portability (single header file, which can be distributed with the library). And since the XML requirements are quite limited, it remained as it is. Maybe in the future, I could look at the possibilities to change this.

**Pull request merged**
